In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn.datasets import load_iris

In [17]:
iris=load_iris()
dataframe=pd.DataFrame(data=iris.data,columns=iris.feature_names)
dataframe['Species']=pd.Categorical.from_codes(iris.target,iris.target_names)

In [18]:
dataframe.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

In [19]:
dataframe.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
#dataframe.drop('Id',axis=1,inplace=True)

In [20]:
dataframe.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

In [21]:
dataframe.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [22]:
x=dataframe.drop(columns=['Species'])

In [23]:
x.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [24]:
y=dataframe['Species']

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score

In [27]:
model=GaussianNB()

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [31]:
conf=confusion_matrix(y_test,y_pred)
rec=recall_score(y_test,y_pred,average="macro")
acc=accuracy_score(y_test,y_pred)
pre=precision_score(y_test,y_pred,average="macro")
print(conf)
print(rec)
print(acc)
print(pre)
print(1-acc)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
1.0
1.0
0.0


In [32]:
# Options for average:

# Value	What it means in simple terms
# "binary"	Used only for binary classification (default). Assumes labels are 0 and 1, and treats label 1 as the positive.
# "macro"	Calculate precision for each class, then take the average (treats all classes equally).
# "micro"	Combines all TP, FP, FN before calculating precision (good for imbalanced classes).
# "weighted"	Like macro, but gives more weight to bigger classes (useful if classes have different sizes).
# None	Returns precision for each class separately (as a list/array).